on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@e97344095b099e1d729fe97429078c9975921d8a  # v2.6.2
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
