on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@22ddf09dfabb443adddfb9f861b7d41a787d6b1a  # v3.0.3
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
