on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@e5af21e4ae37af089a73bb032e10b78b0e746174  # v3.0.1
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
