on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tox:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@e97344095b099e1d729fe97429078c9975921d8a  # v2.6.2
    with:
      coverage: 'codecov'
      envs: |
        - linux: py39
        - linux: py310
        - linux: py311
        - linux: py312
        - linux: py313
        - macos: py39
        - macos: py310
        - macos: py311
        - macos: py312
        - macos: py313
        - windows: py39
        - windows: py310
        - windows: py311
        - windows: py312
        - windows: py313
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
